// Node.js built-in modules

// Third-party libraries
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
// import { DM_Sans } from "next/font/google";

// Internal/relative imports
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import { ThemeProvider } from "@/components/providers/theme-provider";

// CSS/asset imports
import "./globals.css";

// const dmSans = DM_Sans({
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ${dmSans.className}
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Nuqs adapter. */}
          <NuqsAdapter>
            {/* tRPC context. */}
            <TRPCReactProvider>
              {children} <Toaster />
            </TRPCReactProvider>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
